---

info:
  description: Training configuration repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@eureka-ungrazed-washaway.cfapps.io/eureka

---
spring:
  profiles: cloud
eureka.instance.hostname: ${vcap.application.uris[0]}
eureka.instance.nonSecurePort: 80
