---

info:
  description: Training configuration repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@eureka-ungrazed-washaway.cfapps.io/eureka

---
spring:
  profiles: cloud
  ${vcap.application.uri[0]}
  nonSecurePort: 80
